openapi: 3.0.3
info:
  title: ChattyCar notifications service
  description: Microservice handling notifications database in ChattyCar project
  version: 1.0.0
servers:
  - url: http://localhost:9004
    description: Development server
paths:
  /notifications:
    post:
      summary: Create a new notification
      requestBody:
        description: Information of the notification
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/newNotification'
      responses:
        400:
          description: Notification in request is not correct
        201:
          description: Notification is created, sent notification created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/notification'

  /notifications/user/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
        description: ID of the user
    get:
      summary: Get user notifications
      responses:
        200:
          description: Sent user notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/notification'
    delete:
      summary: Delete all notifications of this user
      responses:
        200:
          description: All notifications are deleted

components:
  securitySchemes:
    authentication:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    newNotification:
      type: object
      properties:
        user_id:
          type: integer
        trip_id:
          type: integer
        date:
          type: string
          description: Date in ISO 8601, YYYY-MM-DD
        notification_text:
          type: string
      example:
        user_id: 12
        trip_id: 38
        date: 2022-10-24
        notification_text: Votre demande de voyage a été acceptée

    notification:
      type: object
      properties:
        notification_id:
          type: integer
        user_id:
          type: integer
        trip_id:
          type: integer
        date:
          type: string
          description: Date in ISO 8601, YYYY-MM-DD
        notification_text:
          type: string
      example:
        notification_id: 1
        user_id: 12
        trip_id: 38
        date: 2022-10-24
        notification_text: Votre demande de voyage a été acceptée