### Create user
POST http://localhost:9000/users
Content-Type: application/json

{
  "email": "nico@gmail.com",
  "firstname": "nicolas",
  "lastname": "poppe",
  "password": "password123"
}

### Create user zoe
POST http://localhost:9000/users
Content-Type: application/json

{
  "email": "zoe@gmail.com",
  "firstname": "zoe",
  "lastname": "levaux",
  "password": "123password321"
}

### get user
GET http://localhost:9000/users?email=nico@gmail.com


### Connect user
POST http://localhost:9000/auth
Content-Type: application/json

{
  "email": "nico@gmail.com",
  "password": "password123"
}

> {%
 client.global.set("userToken", response.body);
 %}

### Connect user zoe
POST http://localhost:9000/auth
Content-Type: application/json

{
  "email": "zoe@gmail.com",
  "password": "123password321"
}

> {%
 client.global.set("userTokenZoe", response.body);
 %}

### get user by id
GET http://localhost:9000/users/2
Authorization: {{userToken}}

### update user password
PUT http://localhost:9000/users
Content-Type: application/json
Authorization: {{userToken}}

{
  "email": "nico@gmail.com",
  "password": "oncle22"
}

### update user
PUT http://localhost:9000/users/1
Content-Type: application/json
Authorization: {{userToken}}

{
  "id": 1,
  "email": "nico@gmail.com",
  "firstname": "nicolas",
  "lastname": "dominique"
}

### delete user
DELETE http://localhost:9000/users/1
Authorization: {{userToken}}