GET http://localhost:9005/trips

###
GET http://localhost:9005/trips?destinationLon=4.451009&destinationLat=50.849372

###
GET http://localhost:9005/trips?originLon=8.548796&originLat=52.142598

###
GET http://localhost:9005/trips?originLon=8.548796&originLat=52.142598&destinationLon=4.451009&destinationLat=50.849372

###
GET http://localhost:9005/trips?departureDate=2022-10-25

###
GET http://localhost:9005/trips?departureDate=2022-10-25&destinationLon=4.451009&destinationLat=50.849372

###
GET http://localhost:9005/trips?departureDate=2022-10-25&originLon=8.548796&originLat=52.142598

###
GET http://localhost:9005/trips?departureDate=2022-10-25&originLon=8.548796&originLat=52.142598&destinationLon=4.451009&destinationLat=50.849372

### /trips/{id}
### GET
GET http://localhost:9005/trips/1

###
GET http://localhost:9005/trips/0

### /trips/{id}/driver
GET http://localhost:9005/trips/12/driver

###
GET http://localhost:9005/trips/0/driver

###
GET http://localhost:9005/trips/1/passenger